CREATE TABLE matches (
	ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	RED1 INT,
	RED2 INT,
	RED3 INT,
	BLUE1 INT,
	BLUE2 INT,
	BLUE3 INT,
	MATCHNUMBER INT,
	RED_POINTS INT,
	BLUE_POINTS INT,
	EVENT VARCHAR(20)
);
--;;
CREATE TABLE team_matches (
	ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	TEAM INT,
	AUTOGEARS INT,
	LINECROSSED BOOLEAN,
	SHOTS INT
);
--;;
CREATE TABLE teams (
	ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	NUMBER VARCHAR(5),
	NAME VARCHAR(63),
	PRIMARY_COLOR VARCHAR(7),
	SECONDARY_COLOR VARCHAR(7)
);
